"""Constants for data validation"""

EQUIPMENT_TYPES = {
    'Access Control System', 'CCTV', 'Air Compressor', 'Air Cooled Chiller', 'Air Curtain',
    'Air Handling Unit', 'Air Handling Unit-Residential', 'Aircraft Warning Lights Services',
    'Aluminum Door', 'ATS Panel', 'BMU Cradle', 'Boiler / Calorifier', 'Boom Lift',
    'Booster pump', 'Break Pressure Tank', 'Breakers and Isolators', 'Buffer Tank',
    'Building Management System', 'Bullet camera', 'Busbar', 'Calorifier Pump',
    'Capacitor bank', 'Car park shade cleaning', 'Carpentry accessories',
    'Carpentry Inspection', 'Cassette Type DX Unit', 'CAT-5 Pump', 'CCTV',
    'Central Battery system', 'Chemical dosing pump', 'Chemical dosing unit',
    'Chilled water chemical dosing system', 'Chilled Water Circulation Pump',
    'Chilled Water Leak detection system', 'Chilled water piping', 'Chilled water pump',
    'Chlorine Dosing System', 'Circulation pump', 'Close Control Unit - DX type',
    'Close Control Unit Chilled water type', 'CO Sensor', 'Cold Water Booster Pump',
    'Cold Water Circulation Pump', 'Cold Water Reclaimed Pump', 'Compressed air system',
    'Condenser Unit', 'Condenser water chemical dosing system', 'Condenser water pump',
    'Constant air volume unit', 'Control Panel', 'Control Panel Board', 'Cooling Tower',
    'Crack Filling Works', 'Crane', 'DB-FM', 'DDC Panel', 'Deluge system',
    'Diesel fire pump', 'Distribution Board', 'Dock leveller', 'Dome camera',
    'Domestic Water Filtration System', 'Domestic water filtration system BCWS',
    'Domestic water filtration system GWS', 'Domestic water filtration system Hot water line',
    'Domestic water filtration system MCWS', 'Domestic Water Pump', 'Drainage line cleaning',
    'Drawer and Doors', 'Dry Air Cooler', 'Dry pipe sprinkler system', 'Duct and Diffuser',
    'Ducted Split DX Unit', 'Ducted Split DX Unit-Residential', 'Ductless split unit',
    'Ductless split unit-Residential', 'DVR', 'Earthing system', 'Ecology unit',
    'Electric fire pump', 'Electric Fire Pump Panel', 'Electrical accessories',
    'Electrical Inspection', 'Electrical Lighting Fixtures', 'Electro mechanical system',
    'Elevator', 'Emergency / Exit Lighting System', 'Emergency cabinet', 'Emergency lamp',
    'Emergency submain distribution board', 'Escalator', 'Exhaust Fan',
    'Expansion tank', 'External filter pump', 'Extinguisher Automatic',
    'Extinguisher CO2', 'Extinguisher dry chemical powder', 'Extract Fan',
    'Extract Fan-Residential', 'Facade cleaning', 'Facade light control panel',
    'False Ceiling Works', 'Fan Coil Unit', 'Fan Coil Unit -Residential',
    'Fasade light control panel', 'Feeder Pillar Panel', 'Fertilizer Control Panel',
    'Fertilizer Pump', 'Filter', 'Filtration pump', 'Filtration System Control Panel',
    'Fire Alarm Control Panel', 'Fire Alarm System', 'Fire curtains',
    'Fire Fighting System', 'Fire hose reel', 'Fire hydrant', 'Fire rated rolling shutter',
    'Fire suppression system', 'Fire Telephone System', 'Fire water tank',
    'Floor drain, gulley, gutter', 'FM 200', 'Foam system', 'Folding Doors',
    'Forklift', 'Fresh Air Handling Unit', 'Gas detector panel', 'Gas sensor',
    'Gas tank', 'Gas warning alarm', 'Gate Barrier', 'Generator',
    'Generator Control Panel', 'Glass Doors', 'Glass Windows', 'Goods lift',
    'Grey Water System Filter', 'Heat detector', 'Heat Exchanger', 'Heat Recovery Unit',
    'Heater-Swimming Pool water', 'High speed shutter', 'Hose and land valve',
    'Hot water Pump', 'Hot Water Pump control panel', 'Hot water recirculation pump',
    'Hot Water System', 'HVAC accessories', 'HVAC Inspection', 'Incomer',
    'Indoor plants', 'Indoor unit-DX type', 'Internet system', 'Irrigation pump',
    'Irrigation sprinkler system control panel', 'Irrigation System Control Panel',
    'Jacuzzi Heater', 'Jacuzzi system', 'Jet Fan', 'Jet pump', 'Jockey fire pump',
    'Jockey Fire Pump Control Panel', 'Kitchen Cabinet', 'Kitchen Hood',
    'Landing valves', 'Landscaping Services', 'Legionella test',
    'Lift pressurization fan', 'Lighting & Power', 'Lighting Control System',
    'Low Temperature Hot Water Circulation Pump', 'LPG Gas system', 'LV Panel',
    'Main Distribution Board', 'Main STP Control Panel', 'Make up Air Fan / Fresh Air Fan',
    'Make up pump', 'Manual call point', 'Manual Transfer Switch',
    'Master Control Panel Heater', 'Microbiological test', 'Monitor',
    'Motor Control Center', 'Motor Control Panel', 'Multi Detector', 'Multi Split unit',
    'Network video recorder', 'Packaged Air conditioner', 'Painting Works',
    'Pest control', 'Photo Cell', 'Plumbing accessories', 'Plumbing Inspection',
    'Pole Lights', 'Portable fire extinguishers', 'Power Distribution Unit',
    'Power socket', 'Pre action Sprinkler', 'Preaction sprinkler system',
    'Pressure vessel', 'Pressurization unit', 'Public address system', 'PUMP',
    'Radiant Cooling System', 'Receptionist Services', 'Refrigerant Leak Detector',
    'Refrigeration Unit', 'Repeater panel', 'Revolving Door', 'Roller Shutter',
    'Roof cleaning', 'Sanitary Wares & Fittings', 'Sauna unit', 'Scissor Lift',
    'Security Services', 'Sensors', 'Sewage pump & Pits', 'Sewerage cleaning',
    'Signage System', 'Sliding Door', 'Smoke detector', 'Smoke extract fan',
    'Smoke ventilator door', 'Softener Water Storge Tank', 'Soil & Vent Pipe Network',
    'Solar panel', 'Solar tube light', 'Sounder/Bell', 'Spot cooling system',
    'Staircase pressurization fan', 'Steamer unit', 'STP Pumping system',
    'Sub Main Distribution Board', 'Submersible pump', 'Swimming Pool',
    'Swimming pool pump', 'Swimming pool water heater unit', 'Switch Board',
    'Tap of box', 'Thermostat', 'Tile works', 'Toilet Exhaust Fan', 'Transfer Pump',
    'Transformer', 'Travellator', 'Trench Unit', 'Uninterrupted Power Supply',
    'UPS Feeder Panel', 'Vacuum degasser', 'Variable Air Volume Unit',
    'Ventilation Fan', 'VESDA Panel', 'VFD / VSD', 'VRF / VRV Indoor unit',
    'VRF Outdoor Unit', 'VRV Outdoor Unit', 'Wardrobe', 'Waste & Garbage disposal',
    'Water analysis', 'Water Cooled Chiller', 'Water Cooler', 'Water Feature Lights',
    'Water Features Filter pump', 'Water Features Internal filter pump',
    'Water Features Internal pump', 'Water heater', 'Water softener system',
    'Water Supply Network', 'Water Tank', 'Water Transfer pump',
    'Wet pipe sprinkler system', 'Wet riser', 'Window Air conditioner',
    'Window Air conditioner-Residential', 'Wooden Doors', 'Zone control valves'
}

EQUIPMENT_CLASSES = {
    'Access control & Security', 'Access Equipment', 'Admin', 'Building Management',
    'Carpentry', 'CCTV', 'Civil', 'Electrical', 'Fire Alarm & Fire Fighting',
    'HVAC', 'Information Tech & Communication', 'LPG Central Gas System',
    'Mechanical', 'Plumbing', 'Public address system', 'Soft services',
    'Swimming pool'
}
